# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Mayur Bhangale
email: mayurbhangale96@gmail.com
description: > # this means to ignore newlines until "url:"
  Snippets from Mayur
footer_text: >
  Powered by <a href="http://jekyllrb.com/" target="_blank">Jekyll</a>
  Hosted by <a href="https://pages.github.com/" target="_blank">GitHub Pages</a>.

url:  https://mayurbhangale.github.io
baseurl:
last_updated: # leave blank if you don't want to display last updated

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
github_username: mayurbhangale
twitter_username: mayurcb
linkedin_username: mayurbhangale
medium_username: mayurbhangale96

contact_note: >
  I'm mostly active on Twitter but you can also reach out to me on LinkedIn.

google_analytics: UA-148060511-1 # out your google-analytics code

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: Mayur Bhangale
blog_description: Snippets from Mayur

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname:  mayurbhangale

# Optional features
show_social_icons:  false
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/

news_limit: 5

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
highlighter: pygments

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jekyll/scholar
    - jemoji



# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "1.12.4"
katex_version: "0.9.0"
anchorjs_version: "3.2.2"
